### ISSUE TITLE
Existing attributes in user are removed on edit -> save

### ISSUE THREAD

**Issue by tokland** [dhis2/user-app#33]
Users, like other entities, can have [attributes](https://play.dhis2.org/2.30/dhis-web-maintenance/index.html#/edit/otherSection/attribute/add). AFICS, user-app does not render attribute values like the [old version](https://play.dhis2.org/2.29/dhis-web-maintenance-user/showUpdateUserForm.action?id=240854) did (it should, I guess); but, more importantly, it clears the existing value of the field `attributeValues` when a user is updated.

In fact, it's my understanding that a GET should query as starting point with `fields=:owner` ([example](https://play.dhis2.org/2.30/api/users/xE7jOejl9FI.json?fields=:owner)) and later send in the PUT payload, otherwise, all those fields will be cleared.

**Comment by HendrikThePendric** [comment]
This issue was addressed in #36 and support for editing attributes was added in #39. Closing this one.
